segmentio/analytics-java

src/main/java/com/github/segmentio/flush/Flusher.java
=> correctly respect return value of Requester#send

analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java
=> Correctly check flushInterval. 

analytics-core/src/main/java/com/segment/analytics/messages/MessageBuilder.java, analytics-core/src/test/java/com/segment/analytics/messages/MessageBuilderTest.java
=> Allow passing custom timestamps

analytics-core/pom.xml, analytics/pom.xml
=> Change findbugs scope to provided

analytics-sample/src/main/java/sample/Sample.java, analytics/src/main/java/com/segment/analytics/Platform.java, analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
=> Correct shutdown behaviour

analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java, analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java
Also refactors some of the AnalyticsClient code and improves test
documentation.
=> Add a limit to number of retries

analytics-sample/pom.xml, analytics/src/main/java/com/segment/analytics/Analytics.java
=> Make threadFactory option in Builder public

pom.xml
Some indentation fixes.
Closes #77
=> Configuration for compilation with dependencies

analytics-sample/src/main/java/sample/BlockingFlush.java, analytics-sample/src/main/java/sample/Main.java, analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/main/java/com/segment/analytics/Plugin.java, analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java
Plugins are able to able to consolidate logic around building an analytics client into a single class.
=> Add Plugins

analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java, analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java
This makes it easier to write plugins that need callbacks since each
can independently set it's own callback.
=>   Add support for multiple callbacks.

.buildscript/cli.sh, .buildscript/deploy_snapshot.sh, .buildscript/e2e.sh, .circleci/Makefile, .circleci/config.yml, analytics-cli/src/main/kotlin/cli/Main.kt
This integrates the testing harness with the Java library. The harness invokes the cli package with fixtures and verifies that the library was able to send those messages to a webhook connected to the project succesfully.
https://paper.dropbox.com/doc/Libraries-End-to-End-Testing-Harness-dnotyIVIGYR7lnO1LcZtM
=> Add End to End tests.

analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java, analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java
As outlined in https://paper.dropbox.com/doc/Analytics-library-guidelines-2trBhLKQD4Soz4VatvuGR#:uid=189560039280582553736180&h2=Handling-Network-Errors; our retry strategy should be:
1. Retry network errors (socket timed out, etc.)
2. Retry server errors (HTTP 5xx)
3. Do not retry client errors (HTTP 4xx)
1. Except HTTP 429.
We had overlooked that Retrofit returns HTTP error as it's own type and this was not covered by the `NETWORK` error type. This patch fixes our retry logic so that we retry in case of HTTP 5xx errors and HTTP 429 errors.
=> Improve Retry Logic

.buildscript/e2e.sh, .circleci/config.yml, analytics-core/pom.xml, pom.xml
This required updating the version of `auto` and `kotlin` we use. Lastly, we updated the library-e2e-tester to run more tests.
Ref: LIB-489
=> Test against multiple JDK versions.

analytics-sample/src/main/java/sample/GzipRequestInterceptor.java, analytics-sample/src/main/java/sample/Main.java
Rather than support gzip natively, I've added an example to show how customers can do this themselves. I'll add this to our public facing docs.
=> Add Gzip example

pom.xml
Partial fix for https://segment.atlassian.net/browse/LIB-678
See: https://issues.apache.org/jira/browse/SUREFIRE-1588 for root cause
=> Update surefire version and workaround for latest java8

README.md
=> adding circleci badge

.gitignore, pom.xml
=> Upgrading okhttp client

pom.xml
=> Upgrading okhttp

.circleci/config.yml, analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java, analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java
Closes https://github.com/segmentio/analytics-java/issues/244
=> Backpressure calc

analytics-cli/pom.xml, analytics-core/pom.xml, analytics-sample/pom.xml, analytics-spring-boot-starter/pom.xml, analytics/pom.xml, analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java, analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java, pom.xml
=> Batching batches

analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java, pom.xml
=> should prioritize uploadURL over endpoint

analytics-core/src/main/java/com/segment/analytics/messages/PageMessage.java, analytics-core/src/test/java/com/segment/analytics/messages/PageMessageTest.java
Ref: https://segment.zendesk.com/hc/en-us/requests/440059
=> update PageMessage to allow for setting of category

analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
Added throw interrupted exception when event exceeds 32kb to stop Thread "enqueue" method on "AnalyticsClient" to stop the current Thread
=> Added throw interrupted exception when event exceeds 32kb to stop Thread

analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
Change line structure from exception on AnalyticsClient to fix issue on CircleCI
=> Change line structure from exception on AnalyticsClient

.circleci/config.yml
=> Add test semerujdk11

analytics-core/src/test/java/com/segment/analytics/messages/BatchTest.java
Fix update library from #360 and #362
=> Change validation on BatchTest on createWithSentAtNull

.circleci/config.yml, pom.xml
=> Update dependabot library and remove semeru image test for circleci

analytics-cli/pom.xml, analytics-core/pom.xml, analytics-sample/pom.xml, analytics-spring-boot-starter/pom.xml, analytics/pom.xml
Signed-off-by: Olivier Lamy <olamy@apache.org>
=> in dev projects must use -SNAPSHOT or depends on -SNAPSHOT parent

pom.xml
<kotlin.version>1.7.20</kotlin.version>
<spotless.version>2.27.2</spotless.version>
<auto.version>1.10</auto.version>
=> Update libraries to fix test

CHANGELOG.md, analytics-core/src/main/java/com/segment/analytics/messages/Batch.java, analytics-core/src/test/java/com/segment/analytics/messages/BatchTest.java, analytics/src/main/java/com/segment/analytics/Analytics.java, analytics/src/main/java/com/segment/analytics/AnalyticsRequestInterceptor.java, analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java, analytics/src/test/java/com/segment/analytics/AnalyticsRequestInterceptorTest.java, analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java
- Remove writeKey from header
- Add writeKey on payload(batch)
- Add instanceId
I added the writeKey on AnalyticsClient constructor class to put on payload (Batch class on this library).
=> Remove writeKey from header, add writeKey on payload(batch)

.github/workflows/coverage.yaml, .github/workflows/e2e.yaml, .github/workflows/java11.yml, .github/workflows/java17.yml, .github/workflows/java8.yml, .github/workflows/publish.yaml, .github/workflows/snyk.yaml
- Add github actions, is necessary change the configuration on some '.sh'  files because still using circleci configuration
- I commented the lines that report the failure build on Slack channel.
=> Convert circleci to github actions
