analytics-core/src/main/java/com/segment/analytics/messages/AliasMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/Batch.java
analytics-core/src/main/java/com/segment/analytics/messages/GroupMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/IdentifyMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/Message.java
analytics-core/src/main/java/com/segment/analytics/messages/MessageBuilder.java
analytics-core/src/main/java/com/segment/analytics/messages/ScreenMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/TrackMessage.java
analytics-sample/src/main/java/sample/Sample.java
analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
analytics/src/main/java/com/segment/analytics/internal/FlushMessage.java

So that users dont have to cast their maps to < String, Object > . 
Closes #63

Relax signature of map types

---

analytics/src/main/java/com/segment/analytics/Platform.java

We don't really ever update the thread name from "Analytics-Idle" to
anything else, so let's just leave it as "Analytics".

Fix Thread name

---

analytics-core/src/main/java/com/segment/analytics/gson/ISO8601DateAdapter.java
analytics-core/src/main/java/com/segment/analytics/gson/Iso8601Utils.java
analytics/src/main/java/com/segment/analytics/Analytics.java

Previously the library was incorrectly formatting Date objects for the
Segment API.
This was likely due to SimpleDateFormat's inability to understand the
ISO 8601 format "yyyy-MM-dd'T'HH:mm:ssZ"
http://stackoverflow.com/a/7910898
Copied from Moshi
https://github.com/square/moshi/blob/1c6bebac1d0c8c7e455b5db58832f2ce10581222/adapters/src/main/java/com/squareup/moshi/Iso8601Utils.java

Fix ISO 8601 formatting.

---

analytics/src/main/java/com/segment/analytics/Analytics.java

Previously the raw retrofit message was being supplied as the "format"
argument to the log provided by the client.
This was problematic because this will caused most default
implementations of log to call String.format(msg), with potentially
unescaped "formatting" characters.
e.g. `analytics.enqueue(TrackMessage.builder("
Test").userId("1%5z90951"))` will fail the batch with this message:
retrofit.RetrofitError: Conversion = 'z'
because it String.format thinks %5z is formatting directive.
This change fixes it so that "%s" is passed as the format of the log
message, and the retrofit message is substituted in place.

Supply Retrofit log messages to log correct.

---

analytics/src/main/java/com/segment/analytics/Analytics.java
analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java

This enables use cases such as:
* pointing the client to a mock web server for testing
* pointing the client to proxy
Rebase + fixes of #87 (thanks @derarmin!)

Make endpoint configurable.

---

analytics-core/src/main/java/com/segment/analytics/messages/Message.java
analytics-core/src/main/java/com/segment/analytics/messages/MessageBuilder.java
analytics-core/src/test/java/com/segment/analytics/messages/MessageBuilderTest.java
analytics/src/main/java/com/segment/analytics/internal/FlushMessage.java

To match the anonymous ID API, message IDs can currently only be UUIDs.
Also adds some tests for anonymous ID.
Closes #30

Add APIs to allow setting a custom message ID.

---

analytics/src/main/java-templates/com/segment/analytics/internal/AnalyticsVersion.java

Previously the version was being sent as "analytics/<version>" instead of simply "<version>".

Fix version string.

---

analytics-core/src/main/java/com/segment/analytics/messages/AliasMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/GroupMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/IdentifyMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/Message.java
analytics-core/src/main/java/com/segment/analytics/messages/MessageBuilder.java
analytics-core/src/main/java/com/segment/analytics/messages/PageMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/ScreenMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/TrackMessage.java
analytics-core/src/test/java/com/segment/analytics/messages/MessageBuilderTest.java
analytics/src/main/java/com/segment/analytics/internal/FlushMessage.java
pom.xml

This is a breaking change, as previously the `messageId` and `anonymousId` methods used to return `UUID`, but now they return `String`.

Allow setting String ids in addition to UUIDs.

---

.buildscript/e2e.sh
.circleci/config.yml

Uses the new version of the e2e testing tool. Changes described in https://github.com/segmentio/library-e2e-tester/releases/tag/0.2.0.
Additionally it inly runs CI against JDK 8 as the build fails on the latest version.

Update E2E tests to use webhook-e2e.

---

.circleci/config.yml

This uses CI workflows instead of our simpler older setup. This will make it easy to start testing against multiple JDK versions in the future.
Also adds CI dependency caching.

Use Circle CI workflows

---

.circleci/config.yml
Makefile
pom.xml

This lets us verify that we don't accidentally use newer Java APIs unintentionally.

Add Animal Sniffer

---

pom.xml

Remove errorprone from maven-compiler-plugin's dependency, as it has not
been updated to work with Java 11.
ref: LIB-678

Remove errorprone from maven-compiler-plugin

---

.circleci/config.yml

Run e2e tests instead of multi-tests for the scheduled tests

Fix scheduled e2e test jobs

---

analytics-sample/src/main/java/sample/BlockingFlush.java

Hi! A very minor fix, but one that I lost several minutes to tracking down.
I recently was following this BlockingFlush example to integrate into a project and found that the example code fixed here did not compile when copied into the codebase.

Fix sample in javadoc

---

analytics-core/src/main/java/com/segment/analytics/messages/MessageBuilder.java

The `Map<String, ? super Object>` takes values that are of `Object` class only.
This should actually be `Map<String, ? extends Object>`, which can be written in short as `Map<String, ?>`.

Fix integration options map

---

analytics/src/main/java/com/segment/analytics/Analytics.java
analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java
analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java

Configurable retry count

---

analytics-core/src/main/java/com/segment/analytics/messages/MessageBuilder.java
analytics-core/src/test/java/com/segment/analytics/messages/IdentifyMessageTest.java
analytics-core/src/test/java/com/segment/analytics/messages/MessageBuilderTest.java
analytics-core/src/test/java/com/segment/analytics/messages/TrackMessageTest.java

The Java SDK has a rule and corresponding unit tests that would throw if **either** `userId` or `anonymous` were null or empty strings. This was causing issues for Segment customers that needed to set an `anonymousId` and a null `userId` - the `userId` omission would always throw.
According to the Segment spec for [Identify calls](https://segment.com/docs/connections/spec/identify/#identities) and conventions used in [other SDKs](https://segment.com/docs/connections/sources/catalog/libraries/server/node/#identify), events must have either a `userId` or an `anonymousId`.
This PR aligns the Java SDK with the Segment spec and other SDKs:
- removes the individual null/empty checks for `userId` and `anonymousId`; the check will only be performed in MessageBuilder.build()
- changed the check in …

Require either userId or anonymousId (aligns with other Segment SDK conventions)

---

analytics/src/main/java/com/segment/analytics/Analytics.java
analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java

Added a method to the Analytics Builder class forceTlsVersion1() - name subject to change
Usage -
Analytics.Builder builder = Analytics.builder("someKey");
Analytics analytics = builder.userAgent("someUserAgent")
.client(someClient)
.endpoint("some endpoint")
.anotherAlreadyExistingMethod(someParam)
.forceTlsVersion1()
.build();
this new method forces the httpClient to be created using  ConnectionSpec of MODERN_TLS and including Tls Versions: TLS_1_0, TLS_1_1, TLS_1_2, TLS_1_3
Also added a simple test case

Bugfix for TLS version error (protocol not supported error)

---

analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java

Pull request for issue 
https://github.com/segmentio/analytics-java/issues/293
Removing call to failure method on callback object

Removed the line for failure callback method

---

analytics-core/src/main/java/com/segment/analytics/http/SegmentService.java
analytics/src/main/java/com/segment/analytics/Analytics.java
analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java

When setting a custom upload URL in the Analytics builder, users are currently unable to set a URL that does not end in a "/". This is caused by a slight misuse of the Retrofit builder in which the full upload URL is being supplied for the baseUrl.
Retrofit provides a better mechanism for using dynamic URLs via the Url annotation. If this annotation is used over the existing logic, URLs that do not end in a "/" will be allowed.

Call upload URL using Retrofit's @Url annotation

---

analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java

Fix issue #396 
Create a GSON instance without static method helps to create a new serializable object.

Change method static to public to create a GSON instance

---

analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java

Change exception to identify the limited exceed for the message and handle externally.
Fix #397

Change exception to identify the limited exceed for the message

---

analytics/src/main/java/com/segment/analytics/Analytics.java
analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java
analytics/src/test/java/com/segment/analytics/AnalyticsBuilderTest.java
analytics/src/test/java/com/segment/analytics/internal/AnalyticsClientTest.java

Hi there,
I'm getting some issues when upgrading services to Java 17, where previously Gson was able to automatically deserialise things like java.util.Optional, and java.util.Duration, but now gets exceptions due to disallowed reflection.
Can we change Analytics / AnalyticsClient, to allow the GsonBuilder to be passed in, so that consumers can provide TypeAdapters and TypeAdapter factories as needed, for deserialisation of any classes that they'd like to send in analytics messages?

Allow GsonBuilder to be passed in and used through Analytics and AnalyticsClient

---

analytics-sample/src/main/java/sample/BlockingFlush.java

As alluded to in https://github.com/segmentio/analytics-java/issues/261, parties registered when messages are enqueued must be deregistered when those messages complete, otherwise the Phaser's number of parties increases without end.
As such there are certain cases where `BlockingFlush#block`  will hang indefinitely, even once all messages have completed.
Example:
```
00: Phaser initialized;    phase=0, parties=1, arrived=0
01: Enqueue Message 1;     phase=0, parties=2, arrived=0
02: Enqueue Message 2;     phase=0, parties=3, arrived=0
03: arriveAndAwaitAdvance; phase=0, parties=3, arrived=1
04: Complete Message 1;    phase=0, parties=3, arrived=2
05: Complete Message 2;    phase=0, parties=3, arrived=3 (advance)
06: Enqueue Message 4;     phase=1, parties=4, arrived=0
07: Enqueue Message …
```

BlockingFlush: Deregister parties upon message completion

---

analytics-core/pom.xml
analytics-core/src/main/java/com/segment/analytics/messages/GroupMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/IdentifyMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/Message.java
analytics-core/src/main/java/com/segment/analytics/messages/PageMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/ScreenMessage.java
analytics-core/src/main/java/com/segment/analytics/messages/TrackMessage.java
analytics/pom.xml
analytics/src/main/java/com/segment/analytics/AnalyticsRequestInterceptor.java
analytics/src/main/java/com/segment/analytics/internal/FlushMessage.java
analytics/src/main/java/com/segment/analytics/internal/StopMessage.java

Change Nonnull & Nullable annotation to jakarta.annotation

---

pom.xml

`retrofit`, the compile-time dependency of `analytics-core`, has few vulnerabilities in the required version [`2.9.0`](https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit/2.9.0). They are resolved in version [`2.11.0`](https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit/2.11.0), but this version is compiled with Kotlin `1.9.x` (as opposed to `1.7.x` used in this project), so had to bump that as well.

Bump retrofit to fix CVEe
